debug: False
captcha:
  secret: '6Lex-JkqAAAAAIQA0SW4WZUQ9wjU1cYsRpNLwLu'
database:
  user: 'postgres'
  name: 'postgres'
  password: 'secret'
  host: 'localhost'
  port: '5432'
redis:
  host: 'localhost'
  port: '6379'
  topic: 'test'
  db: '0'
  service: 'docfedorov'
  env: 'prod'